# With multi-part yamls, we can specify configs for different profiles.
# To run your app with a specific profile, add this to the IntelliJ's Runner Environment Variables:
# `spring.profiles.active=dev`
spring.config.activate.on-profile: dev
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exposure-site-newsletter_dev
    username: exposure-site-newsletter
  jpa:
    show-sql: true
# Print SQL statements to logs
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---
spring.config.activate.on-profile: test
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exposure-site-newsletter_test
    username: exposure-site-newsletter

---
spring.config.activate.on-profile: prod
spring:
  datasource:
#    All of these are automatically handled by Heroku
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 10
      remove-abandoned: true
      max-idle: 5
      min-idle: 2
      initial-size: 5
---

# If you activate a profile and a particular property does not have a value for that profile, the default value will
# be loaded (e.g. if activated the profile "foo" the server port will be 8080).

# Configs that are not specified for a specific profile, are always loaded

logging.level.org.springframework.jdbc.datasource.init.ScriptUtils: debug
logging.level.org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: error

spring:
  profiles:
    # Making the default profile 'test' helps run tests with the "test" profile without having to resort to
    # annotating all tests with @ActiveProfiles or having to modify gradle env vars to run tests
    # with active.profile=test.
    # https://inspeerity.com/blog/setting-default-spring-profile-for-tests-with-override-option/
    active: test
  jpa:
    database: postgresql
    # We want to use Flyway to manage migrations on all envs
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: postgres
      mode: never
  flyway:
    # Make the migration files to be located on a specific folder. e.g. db/migration/postgresql
    locations: classpath:db/migration/{vendor}